### ISSUE TITLE
3.0.7无法编译

### ISSUE THREAD

**Issue by syreg** [knowbi/knowbi-pentaho-pdi-neo4j-output#1]

**Comment by mattcasters** [comment]
Translation: Cannot compile

Building is easy using Maven:

mvn clean install

You will find the artifact (jar file) in target/Neo4jOutput

**Comment by beexpectedone** [comment]
Could not find artifact pentaho-kettle:kettle-core:jar:6.0-SNAPSHOT in central (http://192.168.46.238:8081/nexus/content/groups/publ
ic) -> [Help 1]
when i  import the project and build with  'mvn clean install' , it  happens

**Comment by beexpectedone** [comment]
Could not find artifact pentaho-kettle:kettle-core:jar:6.0-SNAPSHOT in central (http://192.168.46.238:8081/nexus/content/groups/publ
ic) -> [Help 1]
when i import the project into intellij and build， it happens .

**Comment by mattcasters** [comment]
Just search the nexus:  https://nexus.pentaho.org
Try for example: 6.0.0.0-353
