### ISSUE TITLE
Neo4j Cypher Step - Remove the text box hover

### ISSUE THREAD

**Issue by harlandduman** [knowbi/knowbi-pentaho-pdi-neo4j-output#100]
When hovering on the cypher query text box it displays the whole cypher query in a popup. This gets in the way often when writing cypher in there.

**Comment by uwegeercken** [comment]
Agree. Saw this also. This is very disturbing when writing the query.

**Comment by mattcasters** [comment]
Tweaked things in 4.0.0-beta2, try it.

**Comment by mattcasters** [comment]
A fix was released in version 4.0.0.
