### ISSUE TITLE
Cypher step does not work when the job is called from a command line.

### ISSUE THREAD

**Issue by TeddyTesfaye** [knowbi/knowbi-pentaho-pdi-neo4j-output#111]
Hi,

I tested the cypher step in a simple job and transformation and all works well when used with in spoon. However, when I tried to call the same job from a command prompt, I see the following NullPointerException. Are you aware of this issue?

2019/03/09 01:53:47 - Neo.0 - ERROR (version 8.2.0.0-342, build 8.2.0.0-342 from 2018-11-14 10.30.55 by buildguy) : Error initializing step [Neo]
2019/03/09 01:53:47 - Neo.0 - ERROR (version 8.2.0.0-342, build 8.2.0.0-342 from 2018-11-14 10.30.55 by buildguy) : java.lang.NullPointerException
2019/03/09 01:53:47 - Neo.0 -   at org.pentaho.metastore.stores.delegate.DelegatingMetaStore.getElementTypes(DelegatingMetaStore.java:204)
2019/03/09 01:53:47 - Neo.0 -   at org.pentaho.metastore.stores.delegate.DelegatingMetaStore.getElementTypeByName(DelegatingMetaStore.java:235)
2019/03/09 01:53:47 - Neo.0 -   at org.pentaho.metastore.persist.MetaStoreFactory.loadElement(MetaStoreFactory.java:72)
2019/03/09 01:53:47 - Neo.0 -   at bi.know.kettle.neo4j.steps.cypher.Cypher.init(Cypher.java:70)
2019/03/09 01:53:47 - Neo.0 -   at org.pentaho.di.trans.step.StepInitThread.run(StepInitThread.java:69)
2019/03/09 01:53:47 - Neo.0 -   at java.lang.Thread.run(Thread.java:745)
2019/03/09 01:53:47 - test-plugin - ERROR (version 8.2.0.0-342, build 8.2.0.0-342 from 2018-11-14 10.30.55 by buildguy) : Step [Neo.0] failed to initialize!
2019/03/09 01:53:47 - Transformation - ERROR (version 8.2.0.0-342, build 8.2.0.0-342 from 2018-11-14 10.30.55 by buildguy) : Unable to prepare for execution of the transformation
2019/03/09 01:53:47 - Transformation - ERROR (version 8.2.0.0-342, build 8.2.0.0-342 from 2018-11-14 10.30.55 by buildguy) : org.pentaho.di.core.exception.KettleException:
2019/03/09 01:53:47 - Transformation - We failed to initialize at least one step.  Execution can not begin!
2019/03/09 01:53:47 - Transformation -
2019/03/09 01:53:47 - Transformation -
2019/03/09 01:53:47 - Transformation -  at org.pentaho.di.trans.Trans.prepareExecution(Trans.java:1272)
2019/03/09 01:53:47 - Transformation -  at org.pentaho.di.trans.Trans.execute(Trans.java:738)
2019/03/09 01:53:47 - Transformation -  at org.pentaho.di.job.entries.trans.JobEntryTrans.execute(JobEntryTrans.java:1180)
2019/03/09 01:53:47 - Transformation -  at org.pentaho.di.job.Job.execute(Job.java:680)
2019/03/09 01:53:47 - Transformation -  at org.pentaho.di.job.Job.execute(Job.java:821)
2019/03/09 01:53:47 - Transformation -  at org.pentaho.di.job.Job.execute(Job.java:497)
2019/03/09 01:53:47 - Transformation -  at org.pentaho.di.job.Job.run(Job.java:384)

Thanks,

**Comment by mattcasters** [comment]
This is caused by a bug in Pan/Kitchen in Pentaho Data Integration, not as much in the plugin.
The easiest way to get round this issue is to use the Maitre script to run transformations or jobs.
You can find it in the needful things plugin:  https://github.com/mattcasters/kettle-needful-things
Or download a remix version from www.kettle.be

**Comment by TeddyTesfaye** [comment]
Thank you for response. I will try the Maitre script

**Comment by TeddyTesfaye** [comment]
All worked well as advised above

**Comment by rbortolini** [comment]
I have the same problem, includes the plugin: (https://github.com/mattcasters/kettle-needful-things) following the guidelines and it didn't work.
Does Maitre have the Kettle Environments Plugin to work?

Retordo  CMD : 
C:\Pentaho\Ferramentas\data-integration (8.2.0.0)>teste.bat
DEBUG: Using PENTAHO_JAVA_HOME
DEBUG: _PENTAHO_JAVA_HOME=C:\Program Files\Java\jdk1.8.0_231
DEBUG: _PENTAHO_JAVA=C:\Program Files\Java\jdk1.8.0_231\bin\java.exe

C:\Pentaho\Ferramentas\data-integration (8.2.0.0)>"C:\Program Files\Java\jdk1.8.0_231\bin\java.exe"  "-Xms1024m" "-Xmx2048m" "-XX:MaxPermSize=256m" "-Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2" "-Djava.library.path=libswt\win64" 
"-DKETTLE_HOME=" "-DKETTLE_REPOSITORY=" "-DKETTLE_USER=" "-DKETTLE_PASSWORD=" "-DKETTLE_PLUGIN_PACKAGES=" "-DKETTLE_LOG_SIZE_LIMIT=" 
"-DKETTLE_JNDI_ROOT=" -jar launcher\launcher.jar -lib ..\libswt\win64  -main org.pentaho.di.needful.maitre.Maitre -initial

Dir "C:\Pentaho\Ferramentas\data-integration (8.2.0.0)"\ -f '\samples\teste_neo4j.ktr'

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
13:11:52,319 INFO  [KarafBoot] Checking to see if org.pentaho.clean.karaf.cacheis enabled
13:11:56,426 INFO  [KarafInstance]
*******************************************************************************
*** Karaf Instance Number: 1 at C:\Pentaho\Ferramentas\data-integration (8. ***
***   2.0.0)\.\system\karaf\caches\maitre\data-1                            ***
*** FastBin Provider Port:52901                                             ***
*** Karaf Port:8802                                                         ***
*** OSGI Service Port:9051                                                  ***
*******************************************************************************
nov 17, 2020 1:11:57 PM org.apache.karaf.main.Main$KarafLockCallback lockAquired

INFORMAÃiES: Lock acquired. Setting startlevel to 100
2020-11-17 13:12:00.436:INFO:oejs.Server:jetty-8.1.15.v20140411
2020-11-17 13:12:00.493:INFO:oejs.AbstractConnector:Started NIOSocketConnectorWrapper@0.0.0.0:9051
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.blueprint.NamespaceHandlerRegistererregister
INFORMAÃiES: Registered blueprint namespace handler for http://cxf.apache.org/blueprint/core
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.blueprint.NamespaceHandlerRegistererregister
INFORMAÃiES: Registered blueprint namespace handler for http://cxf.apache.org/configuration/beans
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.blueprint.NamespaceHandlerRegistererregister
INFORMAÃiES: Registered blueprint namespace handler for http://cxf.apache.org/configuration/parameterized-types
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.blueprint.NamespaceHandlerRegistererregister
INFORMAÃiES: Registered blueprint namespace handler for http://cxf.apache.org/configuration/security
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.blueprint.NamespaceHandlerRegistererregister
INFORMAÃiES: Registered blueprint namespace handler for http://schemas.xmlsoap.org/wsdl/
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.blueprint.NamespaceHandlerRegistererregister
INFORMAÃiES: Registered blueprint namespace handler for http://www.w3.org/2005/08/addressing
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.blueprint.NamespaceHandlerRegistererregister
INFORMAÃiES: Registered blueprint namespace handler for http://schemas.xmlsoap.org/ws/2004/08/addressing
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.osgi.CXFExtensionBundleListener addExtensions
INFORMAÃiES: Adding the extensions from bundle org.apache.cxf.cxf-rt-management(195) [org.apache.cxf.management.InstrumentationManager]
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.osgi.CXFExtensionBundleListener addExtensions
INFORMAÃiES: Adding the extensions from bundle org.apache.cxf.cxf-rt-wsdl (198)[org.apache.cxf.wsdl.WSDLManager]
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.osgi.CXFExtensionBundleListener addExtensions
INFORMAÃiES: Adding the extensions from bundle org.apache.cxf.cxf-rt-bindings-xml (200) [org.apache.cxf.binding.xml.XMLBindingFactory, org.apache.cxf.binding.xml.wsdl11.XMLWSDLExtensionLoader]
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.osgi.CXFExtensionBundleListener addExtensions
INFORMAÃiES: Adding the extensions from bundle org.apache.cxf.cxf-rt-bindings-soap (201) [org.apache.cxf.binding.soap.SoapBindingFactory, org.apache.cxf.binding.soap.SoapTransportFactory]
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.blueprint.NamespaceHandlerRegistererregister
INFORMAÃiES: Registered blueprint namespace handler for http://cxf.apache.org/blueprint/bindings/soap
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.osgi.CXFExtensionBundleListener addExtensions
INFORMAÃiES: Adding the extensions from bundle org.apache.cxf.cxf-rt-ws-policy (220) [org.apache.cxf.ws.policy.PolicyEngine, org.apache.cxf.policy.PolicyDataEngine, org.apache.cxf.ws.policy.AssertionBuilderRegistry, org.apache.cxf.ws.policy.PolicyInterceptorProviderRegistry, org.apache.cxf.ws.policy.PolicyBuilder, org.apache.cxf.ws.policy.PolicyAnnotationListener, org.apache.cxf.ws.policy.attachment.ServiceModelPolicyProvider, org.apache.cxf.ws.policy.attachment.external.DomainExpressionBuilderRegistry, org.apache.cxf.ws.policy.attachment.external.EndpointReferenceDomainExpressionBuilder, org.apache.cxf.ws.policy.attachment.external.URIDomainExpressionBuilder, org.apache.cxf.ws.policy.attachment.wsdl11.Wsdl11AttachmentPolicyProvider, org.apache.cxf.ws.policy.mtom.MTOMAssertionBuilder, org.apache.cxf.ws.policy.mtom.MTOMPolicyInterceptorProvider]
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.osgi.CXFExtensionBundleListener addExtensions
INFORMAÃiES: Adding the extensions from bundle org.apache.cxf.cxf-rt-transports-http (202) [org.apache.cxf.transport.http.HTTPTransportFactory, org.apache.cxf.transport.http.HTTPWSDLExtensionLoader, org.apache.cxf.transport.http.policy.HTTP ClientAssertionBuilder, org.apache.cxf.transport.http.policy.HTTPServerAssertion Builder, org.apache.cxf.transport.http.policy.NoOpPolicyInterceptorProvider]
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.blueprint.NamespaceHandlerRegistererregister
INFORMAÃiES: Registered blueprint namespace handler for http://cxf.apache.org/transports/http/configuration
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.blueprint.NamespaceHandlerRegistererregister
INFORMAÃiES: Registered blueprint namespace handler for http://cxf.apache.org/blueprint/simple
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.osgi.CXFExtensionBundleListener addExtensions
INFORMAÃiES: Adding the extensions from bundle org.apache.cxf.cxf-rt-frontend-ja
xws (204) [org.apache.cxf.jaxws.context.WebServiceContextResourceResolver]
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.blueprint.NamespaceHandlerRegistererregister
INFORMAÃiES: Registered blueprint namespace handler for http://cxf.apache.org/blueprint/jaxws
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.blueprint.NamespaceHandlerRegistererregister
INFORMAÃiES: Registered blueprint namespace handler for http://cxf.apache.org/blueprint/jaxrs
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.blueprint.NamespaceHandlerRegistererregister
INFORMAÃiES: Registered blueprint namespace handler for http://cxf.apache.org/blueprint/jaxrs-client
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.blueprint.NamespaceHandlerRegistererregister
INFORMAÃiES: Registered blueprint namespace handler for http://cxf.apache.org/binding/coloc
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.osgi.CXFExtensionBundleListener addExtensions
INFORMAÃiES: Adding the extensions from bundle org.apache.cxf.cxf-rt-transports-local (216) [org.apache.cxf.transport.local.LocalTransportFactory]
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.osgi.CXFExtensionBundleListener addExtensions
INFORMAÃiES: Adding the extensions from bundle org.apache.cxf.cxf-rt-bindings-object (217) [org.apache.cxf.binding.object.ObjectBindingFactory]
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.blueprint.NamespaceHandlerRegistererregister
INFORMAÃiES: Registered blueprint namespace handler for http://cxf.apache.org/blueprint/binding/object
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.blueprint.NamespaceHandlerRegistererregister
INFORMAÃiES: Registered blueprint namespace handler for http://cxf.apache.org/policy
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.blueprint.NamespaceHandlerRegistererregister
INFORMAÃiES: Registered blueprint namespace handler for http://www.w3.org/ns/ws-policy
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.blueprint.NamespaceHandlerRegistererregister
INFORMAÃiES: Registered blueprint namespace handler for http://www.w3.org/2006/07/ws-policy
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.blueprint.NamespaceHandlerRegistererregister
INFORMAÃiES: Registered blueprint namespace handler for http://schemas.xmlsoap.org/ws/2004/09/policy
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.blueprint.NamespaceHandlerRegistererregister
INFORMAÃiES: Registered blueprint namespace handler for http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.blueprint.NamespaceHandlerRegistererregister
INFORMAÃiES: Registered blueprint namespace handler for http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.blueprint.NamespaceHandlerRegistererregister
INFORMAÃiES: Registered blueprint namespace handler for http://www.w3.org/2000/09/xmldsig#
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.blueprint.NamespaceHandlerRegistererregister
INFORMAÃiES: Registered blueprint namespace handler for http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.osgi.CXFExtensionBundleListener addExtensions
INFORMAÃiES: Adding the extensions from bundle org.apache.cxf.cxf-rt-ws-addr (237) [org.apache.cxf.ws.addressing.policy.AddressingAssertionBuilder, org.apache.cxf.ws.addressing.policy.UsingAddressingAssertionBuilder, org.apache.cxf.ws.addressing.policy.AddressingPolicyInterceptorProvider, org.apache.cxf.ws.addressing.impl.AddressingWSDLExtensionLoader, org.apache.cxf.ws.addressing.WSAddressingFeature$WSAddressingFeatureApplier, org.apache.cxf.ws.addressing.MAPAggregator$MAPAggregatorLoader]
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.blueprint.NamespaceHandlerRegistererregister
INFORMAÃiES: Registered blueprint namespace handler for http://cxf.apache.org/ws/addressing
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.osgi.CXFExtensionBundleListener addExtensions
INFORMAÃiES: Adding the extensions from bundle org.apache.cxf.cxf-rt-ws-security (239) [org.apache.cxf.ws.security.policy.WSSecurityPolicyLoader, org.apache.cxf.ws.security.cache.CacheCleanupListener]
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.osgi.CXFExtensionBundleListener addExtensions
INFORMAÃiES: Adding the extensions from bundle org.apache.cxf.cxf-rt-ws-rm (241)[org.apache.cxf.ws.rm.RMManager, org.apache.cxf.ws.rm.policy.RMPolicyIntercepto rProvider, org.apache.cxf.ws.rm.policy.RM10AssertionBuilder, org.apache.cxf.ws.rm.policy.RM12AssertionBuilder, org.apache.cxf.ws.rm.policy.WSRMP12PolicyLoader,org.apache.cxf.ws.rm.policy.MC11PolicyLoader, org.apache.cxf.ws.rm.policy.RSPPolicyLoader]
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.blueprint.NamespaceHandlerRegistererregister
INFORMAÃiES: Registered blueprint namespace handler for http://cxf.apache.org/ws/rm/manager
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.blueprint.NamespaceHandlerRegistererregister
INFORMAÃiES: Registered blueprint namespace handler for http://schemas.xmlsoap.org/ws/2005/02/rm/policy
nov 17, 2020 1:12:01 PM org.apache.cxf.bus.osgi.CXFExtensionBundleListener addExtensions
INFORMAÃiES: Adding the extensions from bundle org.apache.cxf.cxf-rt-javascript(242) [org.apache.cxf.javascript.JavascriptServerListener]
nov 17, 2020 1:12:01 PM org.pentaho.caching.impl.PentahoCacheManagerFactory$RegistrationHandler$1 onSuccess
INFORMAÃiES: New Caching Service registered
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Pentaho/Ferramentas/data-integration%20(8.2.0.0)/launcher/../lib/slf4j-log4j12-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Pentaho/Ferramentas/data-integration (8.2.0.0)/plugins/pentaho-big-data-plugin/lib/slf4j-log4j12-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.

SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]

C:\Pentaho\Ferramentas\data-integration (8.2.0.0)>
