### ISSUE TITLE
Allow multiple hosts in the Neo4j Connection

### ISSUE THREAD

**Issue by rhaces** [knowbi/knowbi-pentaho-pdi-neo4j-output#121]
Currently only one host can be used as the connection host, however for cluster environment it is good to allow multiple hosts, specially when there is not a single "round robin" type of hostname, to avoid not being able to connect to a cluster when the host used is down (and the cluster is up).

This is done through with the routingDriver method (https://neo4j.com/docs/api/java-driver/current/org/neo4j/driver/v1/GraphDatabase.html#routingDriver-java.lang.Iterable-org.neo4j.driver.v1.AuthToken-org.neo4j.driver.v1.Config-)

**Comment by mattcasters** [comment]
see: https://github.com/mattcasters/kettle-neo4j-core/issues/1

**Comment by mattcasters** [comment]
In the 5.0-beta2 preview release we now also have the option to specify multiple URLs allowing all sorts of flexibility.  Because of this I'm going to close this case.
