### ISSUE TITLE
Allow setting the Use Routing with Variable

### ISSUE THREAD

**Issue by rhaces** [knowbi/knowbi-pentaho-pdi-neo4j-output#122]
The connection details has a checkbox to use routing in the connection. For projects where there are environments that are single node and environments that are clustered, this would force that the connection metastore be changed depending what environment.

The ideal scenario would be that the connection can detect an environment variable to decide if it should use routing or not.

**Comment by mattcasters** [comment]
Was implemented in 4.1.x
