### ISSUE TITLE
Enhance Get Fields button to reformat Neo4j Property names to the standard

### ISSUE THREAD

**Issue by davidlrosenblum** [knowbi/knowbi-pentaho-pdi-neo4j-output#13]
When using the Get Fields button the fields are brought over exactly as in the source.
Is it possible to reformat the fields to
1)Capitalize the all words after a space or _
2)Make first character lower case (if not a number)
3)Remove spaces and _ concatenate the words together.
e.g Text Area 1 becomes textArea1
       My_Silly_Column becomes mySillyColumn

**Comment by mattcasters** [comment]
so initCap on the words, remove spaces, tabs, special characters and _
Then make first character lowercase.

**Comment by mattcasters** [comment]
Give 3.5.0 a try and if it works to your liking, close this issue.
Thanks!
