### ISSUE TITLE
How to Optimize Batch Insertion Speed

### ISSUE THREAD

**Issue by yypcd** [knowbi/knowbi-pentaho-pdi-neo4j-output#130]
![image](https://user-images.githubusercontent.com/42907856/60417317-ae5a2b00-9c12-11e9-97cf-9e7b9d2f8316.png)
speed only 16 bars per second， Can you give me some advice? How to import mysql data to neo4j faster?

**Comment by mattcasters** [comment]
It really depends on how many nodes and relationships you're merging into Neo4j.
In the case of the Graph output step, make sure indexes are present on the primary key fields of the nodes.
Alternatively if it's a migration of data we're talking about, use the Neo4j Output step to create nodes and relationships separately.
