### ISSUE TITLE
Neo4j Cypher step - batch size (rows)

### ISSUE THREAD

**Issue by davidfauth** [knowbi/knowbi-pentaho-pdi-neo4j-output#131]
If the number of rows / inputs is less than the batch size, the last transaction is not committed and data is not written to Neo4j.

For example, if the input is 5 rows and the batch size is 3, only 3 rows will be written to Neo4j.
If you set the batch size to 1, all rows will be written.

**Comment by mattcasters** [comment]
Fixed in 4.1.0-beta2
