### ISSUE TITLE
kettle on linux can not write neo4j

### ISSUE THREAD

**Issue by billedven064** [knowbi/knowbi-pentaho-pdi-neo4j-output#132]
use pdi-ce7.0 client with plugin:https://github.com/knowbi/knowbi-pentaho-pdi-neo4j-output
can write neo4j success.
but ,scp the ktr program to the linux server,run the program with error
log4j:ERROR No output stream or file set for the appender named [pdi-execution-appender]
[emp_inf_dev_20190628174509_15970536.log](https://github.com/knowbi/knowbi-pentaho-pdi-neo4j-output/files/3357388/emp_inf_dev_20190628174509_15970536.log)

**Comment by hansva** [comment]
Looks like it is looking for an object in the metastore. Did you also copy the .kettle and .pentaho folder under your home directory to the home directory of the user on the server?
if not copy those over too and try again.
Connection settings for Neo4j are stored in the metastore folder.

**Comment by billedven064** [comment]
I copy the. Pentagon folder 
but I find nothing about neo4j in. kettle folder,so did not copy this folder

**Comment by hansva** [comment]
And does it work now?

**Comment by billedven064** [comment]
run transformation error. the err-msg reference the title's attach files

**Comment by hansva** [comment]
The error clearly states it can't find the metastore object. Check where following parameters point to and move the .pentaho folder to that location
${PENTAHO_METASTORE_FOLDER}

**Comment by billedven064** [comment]
I think the meta in . pentaho folder is different between windows and Linux !
can I editor the meta-data on manual? how?
