### ISSUE TITLE
Label from field uses incorrect row 

### ISSUE THREAD

**Issue by bamaer** [knowbi/knowbi-pentaho-pdi-neo4j-output#148]
When creating labels from fields in the Neo4J Output step, there is a row mismatch. 
The attached transformation creates labels from fields and uses the same field to create a 'country' property. e.g. for the node with label 'Austria', 'Australia' (from the previous row) is used as the country property.
seems identical or related to what was initially reported in #142 

[tr_countries.txt](https://github.com/knowbi/knowbi-pentaho-pdi-neo4j-output/files/3827055/tr_countries.txt)

**Comment by mattcasters** [comment]
Confirmed issues

**Comment by mattcasters** [comment]
Add integration test:  https://github.com/mattcasters/kettle-neo4j-integration/tree/master/tests/neo4j-output-dynamic-labels
