### ISSUE TITLE
5.0-beta1  Transactions only writing to default database 

### ISSUE THREAD

**Issue by yancarlo-perez-neo4j** [knowbi/knowbi-pentaho-pdi-neo4j-output#154]
After selecting non default database name, transactions only write to default database in Neo4j 4.0

Tested with Job Neo4j Cypher Script & Neo4j Cypher step in transformation

**Comment by mattcasters** [comment]
See: https://github.com/mattcasters/kettle-neo4j-core/issues/5

**Comment by mattcasters** [comment]
Tested to be fixed in 5.0-beta2.  Please re-open if you find any more issue with this.
