### ISSUE TITLE
5.0-beta1 Neo4j Connection dialog test is always successful even if Database is shutdown 

### ISSUE THREAD

**Issue by yancarlo-perez-neo4j** [knowbi/knowbi-pentaho-pdi-neo4j-output#155]
Testing against a Neo4j 4.0 database from the Connection dialog is always successful even with the database shutdown.

**Comment by mattcasters** [comment]
I didn't find that verifyConnectivity test but I did ask the database for "RETURN 0" which seems to work fine.  Please re-open if the issue persists after 5.0-beta2
