### ISSUE TITLE
https://www.know-bi.be/blog/easily-load-data-to-neo4j-with-pentaho-data-integration

### ISSUE THREAD

**Issue by gosforth** [knowbi/knowbi-pentaho-pdi-neo4j-output#167]
I tried this example:
https://www.know-bi.be/blog/easily-load-data-to-neo4j-with-pentaho-data-integration
And my PC cannot handle this (Neo4j memory settings: java heap 6g, pagecache 6g... Pentium 7, 16GB ram). tr_beer_relationships.ktr transaction never ends. Screen freezes with query:
```
MATCH (n)
RETURN n
ORDER BY head(labels(n))
LIMIT 300
```
Creating indexes would help (transformation add nodes without indexes)?

**Comment by mattcasters** [comment]
I have no idea what this query is supposed to do, sorry.
