### ISSUE TITLE
The Linux environment executes the .pan.sh command  Error initializing step

### ISSUE THREAD

**Issue by zhangt136** [knowbi/knowbi-pentaho-pdi-neo4j-output#172]
2020/03/04 10:17:38 - updateneo4j.0 - ERROR (version 9.0.0.0-423, build 9.0.0.0-423 from 2020-01-31 04.53.04 by buildguy) : Error initializing step [updateneo4j]
2020/03/04 10:17:38 - neo4j unique.0 - ERROR (version 9.0.0.0-423, build 9.0.0.0-423 from 2020-01-31 04.53.04 by buildguy) : Error initializing step [neo4j unique]
2020/03/04 10:17:38 - new noe4j.0 - ERROR (version 9.0.0.0-423, build 9.0.0.0-423 from 2020-01-31 04.53.04 by buildguy) : Error initializing step [new noe4j]
2020/03/04 10:17:38 - updateneo4j.0 - ERROR (version 9.0.0.0-423, build 9.0.0.0-423 from 2020-01-31 04.53.04 by buildguy) : java.lang.NullPointerException
2020/03/04 10:17:38 - updateneo4j.0 -   at bi.know.kettle.neo4j.steps.cypher.Cypher.init(Cypher.java:72)
2020/03/04 10:17:38 - updateneo4j.0 -   at org.pentaho.di.trans.step.StepInitThread.run(StepInitThread.java:69)
2020/03/04 10:17:38 - updateneo4j.0 -   at java.lang.Thread.run(Thread.java:745)

**Comment by mattcasters** [comment]
It's a bug in Kettle (metastore initialization error in pan) so download a remix version of Kettle at http://www.kettle.be/ and use Maitre to run, not pan.sh
