### ISSUE TITLE
How to integrate into springboot2.x

### ISSUE THREAD

**Issue by suwia** [knowbi/knowbi-pentaho-pdi-neo4j-output#184]
Hello, I have a problem at present ,I want to use Neo4jOutput in Java code, But I don't know how to do, I try to Use KettleEnvironment to load this the pluging but I failed. If you have time to help me ?
Thank you very much!

**Comment by mattcasters** [comment]
Kettle bootstraps plugins from a file called kettle-steps.xml in the kettle-engine.jar file.
If you want to load additional plugins from your classpath you either change that file and point to your copy with XML_FILE_KETTLE_STEPS or you can set a variable called KETTLE_PLUGIN_CLASSES with a comma separated list of extra plugin classes to scan.
The reason for all this is that obviously it takes too long to scan the whole classpath for plugins.

After that setup you can run your transformations and get data from them:

https://wiki.pentaho.com/display/EAI/Executing+a+PDI+transformation
