### ISSUE TITLE
README file with version information.

### ISSUE THREAD

**Issue by datascienceteam01** [knowbi/knowbi-pentaho-pdi-neo4j-output#2]
Please provide a README file with version information / usage instructions if possible. Is this code actually functional with current Pentaho?

**Comment by knowbi** [comment]
Fair point. We'll add a README and examples of how to use in the next couple of days. 
The code has been tested and runs with PDI 6.x and Neo4J 2.x and 3.0.

**Comment by mariobastande** [comment]
Is that documentation available somewhere? thanks

**Comment by mattcasters** [comment]
READ.me updated, wiki documentation updated: https://github.com/knowbi/knowbi-pentaho-pdi-neo4j-output/wiki

**Comment by beexpectedone** [comment]
could you update the document of Neo4j output ---when i try to create relationship ,they halt  and do not build any relationships between the "from node" and  "to node"
![qq 20181228000313](https://user-images.githubusercontent.com/25262023/50486223-ed28e180-0a33-11e9-8f5f-f7cfbc106309.png)

**Comment by beexpectedone** [comment]
![pg](https://user-images.githubusercontent.com/25262023/50486424-dd5dcd00-0a34-11e9-9dc2-4cfac6ae611c.png)

**Comment by beexpectedone** [comment]
@mattcasters  after about 20 minutes , the relationship were not created 
![tt](https://user-images.githubusercontent.com/25262023/50486571-915f5800-0a35-11e9-98ec-be800e9afaaa.png)

**Comment by mattcasters** [comment]
With that many steps you run into transactional issues I think.

**Comment by mattcasters** [comment]
beexpectedone Please do not add to existing issues.
