### ISSUE TITLE
Neo4j Output Step won't load relationship properties

### ISSUE THREAD

**Issue by rhaces** [knowbi/knowbi-pentaho-pdi-neo4j-output#37]
https://github.com/knowbi/knowbi-pentaho-pdi-neo4j-output/blob/c3211b78736a2fae8d641e2bcdeb7c3f7e62aa62/src/main/java/bi/know/kettle/neo4j/steps/output/Neo4JOutputMeta.java#L249

When opening a saved ktr, the relationship properties won't be loaded into the transformation, the line referenced above should point to `relPropsNode` instead of `toPropsNode`

**Comment by mattcasters** [comment]
I tested this and relationship properties seem to work now.
