### ISSUE TITLE
Unable to send messages to server: 远程主机强迫关闭了一个现有的连接(The remote host forcibly closed an existing connection)

### ISSUE THREAD

**Issue by beexpectedone** [knowbi/knowbi-pentaho-pdi-neo4j-output#74]
2018/12/10 22:08:49 - MAX_OVERDUE_DAYS nodes.0 - ERROR (version 6.0.0.0-353, build 1 from 2015-10-07 13.27.43 by buildguy) : Error executing statement: MERGE (n:MAX_OVERDUE_DAYS { 最大逾期天数: {最大逾期天数}});
2018/12/10 22:08:49 - MAX_OVERDUE_DAYS nodes.0 - ERROR (version 6.0.0.0-353, build 1 from 2015-10-07 13.27.43 by buildguy) : Unable to send messages to server: 远程主机强迫关闭了一个现有的连接。
2018/12/10 22:08:49 - 阻xudai 2.0 - 完成处理 (I=0, O=0, R=4957, W=4957, U=0, E=0
2018/12/10 22:08:49 - Add MAX_OVERDUE_DAYS Label.0 - 完成处理 (I=0, O=0, R=9908, W=9908, U=0, E=0
2018/12/10 22:08:49 - 建立base表中节点关系 - ERROR (version 6.0.0.0-353, build 1 from 2015-10-07 13.27.43 by buildguy) : 错误被检测到!
2018/12/10 22:08:49 - MAX_OVERDUE_DAYS nodes.0 - ERROR (version 6.0.0.0-353, build 1 from 2015-10-07 13.27.43 by buildguy) : Error adding nodes 
2018/12/10 22:08:49 - MAX_OVERDUE_DAYS nodes.0 - Unable to send messages to server: 远程主机强迫关闭了一个现有的连接。
2018/12/10 22:08:49 - APPLY_PASS_COUNT nodes.0 - ERROR (version 6.0.0.0-353, build 1 from 2015-10-07 13.27.43 by buildguy) : Unexpected error
2018/12/10 22:08:49 - APPLY_PASS_COUNT nodes.0 - ERROR (version 6.0.0.0-353, build 1 from 2015-10-07 13.27.43 by buildguy) : java.lang.NullPointerException
2018/12/10 22:08:49 - APPLY_PASS_COUNT nodes.0 - 	at bi.know.kettle.neo4j.output.Neo4JOutput.processRow(Neo4JOutput.java:62)
2018/12/10 22:08:49 - APPLY_PASS_COUNT nodes.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2018/12/10 22:08:49 - APPLY_PASS_COUNT nodes.0 - 	at java.lang.Thread.run(Thread.java:745)

**Comment by beexpectedone** [comment]
neo4j server version is 3.2.13

**Comment by beexpectedone** [comment]
@mattcasters could you help me？

**Comment by mattcasters** [comment]
Sorry, this is a Neo4j issue, not a plugin or Kettle problem.  It's probably Neo4j under high stress or running out of memory.
Good luck!
