### ISSUE TITLE
the newest release version can not be used in 6.0.0.0

### ISSUE THREAD

**Issue by beexpectedone** [knowbi/knowbi-pentaho-pdi-neo4j-output#75]
when i download the Neo4JOutput-3.16.0.zip  ,unzip and put it in  plugins\steps  and delete the older Neo4JOutput folder.  but the plugin don't appear in the sidebar  when i restart kettle

**Comment by beexpectedone** [comment]
old version is 0.1 pre-release

**Comment by mattcasters** [comment]
It's caused by an older version of Javassist.  Version 6 didn't support Java 8 yet I think.  
So upgrade lib/javassist-3.12.1.GA.jar with [3.24](http://central.maven.org/maven2/org/javassist/javassist/3.24.0-GA/javassist-3.24.0-GA.jar) and try again.

**Comment by beexpectedone** [comment]
that's the reason.  thanks a lot @mattcasters

**Comment by mattcasters** [comment]
Good luck!
