### ISSUE TITLE
can not insert data

### ISSUE THREAD

**Issue by beexpectedone** [knowbi/knowbi-pentaho-pdi-neo4j-output#83]
![1111](https://user-images.githubusercontent.com/25262023/50501582-2c871a80-0a94-11e9-9d87-1aea5fbac947.png)
 only two steps was  running into transactional , but  the data could not be inserted  .
the neo4joutput step only "read" 1 row and halt 
here is  my  .ktr   

[base_relationships_modify_1.zip](https://github.com/knowbi/knowbi-pentaho-pdi-neo4j-output/files/2713912/base_relationships_modify_1.zip)

**Comment by beexpectedone** [comment]
when i try to go back to version 1.0 , it throws an exception:
ERROR (version 6.0.1.0-386, build 1 from 2015-12-03 11.37.25 by buildguy) : org.neo4j.driver.v1.exceptions.ClientException: Unsupported URI scheme: null

**Comment by mattcasters** [comment]
Sorry beexpectedone, our software is not forward compatible.
