### ISSUE TITLE
Output step has a tendancy to run forever

### ISSUE THREAD

**Issue by codek** [knowbi/knowbi-pentaho-pdi-neo4j-output#90]
If you create a transformation, and then drag in the neo4j output step (With a connectiopn configured) and don't connect it to any hop, the transformation runs forever.

same happens if you have an error in the neo4j output step - you must explicitly stop the transformation even after it's errored.

Using kettle=remix 20190130

**Comment by mattcasters** [comment]
Not seeing this issue anymore in the 4.0 versions.
