### ISSUE TITLE
Neo4jOutput step: index not created

### ISSUE THREAD

**Issue by uwegeercken** [knowbi/knowbi-pentaho-pdi-neo4j-output#92]
The Neo4jOutput step allows to use either a field or a fixed value for the "From Label". The checkbox for "Create Index" is checked. A primary filed is defined.

If a field is used ("From Label Fields"), then the index gets created. If instead a fixed value is used ("From Label Values"), then no index is created. This is valid for both the "From Node" and the "To Node".

**Comment by rhaces** [comment]
> Ha! Nice catch. I've had someone else complain about it but I couldn't reproduce this. Thanks!

And by someone he means me, I just haven't had the time to report. Thanks Uwe.

**Comment by mattcasters** [comment]
The step traditionally simply looked at the first row of data and indexes the label.
Now we have multiple dynamic labels and static labels.  However, we can still only look at the first row.
I continue to regret putting this feature in. J

**Comment by mattcasters** [comment]
I added a warning for dynamic scenarios and "create indexes"

```When creating indexes for nodes with dynamic labels, this step can only look at the first row. We recommend creating the needed indexes separately.```

**Comment by mattcasters** [comment]
A fix was released in version 4.0.0.
