### ISSUE TITLE
Neo4j Output step: changes in step not recognized

### ISSUE THREAD

**Issue by uwegeercken** [knowbi/knowbi-pentaho-pdi-neo4j-output#93]
When the configuration of a step is changed and the step dialog is closed using "OK", then in the gui the title of the transformation window is displayed in bold, indicating that something was changed.
The 4.0.0 Beta 1 version on PDI 8.1 does not show this indicator.

**Comment by uwegeercken** [comment]
Some additional info: Sometimes an update to the step is recognized and sometimes not. Have not found a pattern yet. Anyway, if I click on save, then the settings are correctly stored.

**Comment by mattcasters** [comment]
A fix was released in version 4.0.0.
