### ISSUE TITLE
Neo4j Output step: Fields overlap

### ISSUE THREAD

**Issue by uwegeercken** [knowbi/knowbi-pentaho-pdi-neo4j-output#95]
![grafik](https://user-images.githubusercontent.com/6207140/52145753-3804cd00-2662-11e9-8727-0701d409760c.png)
The fields "Relationship field" (dropdown) and "Relationship value" slightly overlap each other. Please see attached scrrenprint.
PDI 8.1, Neo4j 4.0.0 Beta 1 on Fedora 29 Linux

**Comment by mattcasters** [comment]
A fix was released in version 4.0.0.
