### ISSUE TITLE
Neo4j Output step: Exception when username/password not specified

### ISSUE THREAD

**Issue by uwegeercken** [knowbi/knowbi-pentaho-pdi-neo4j-output#96]
Neo4j requires me to specify a username and password.

I created a new neo4j connection but I did not specify username and password. Clicking on "Test" in the connection dialog results in the message:

Unable to connect to database 'local"

But when you look at the detailed message and scroll down a bit following exception can be found:

Caused by: org.neo4j.driver.v1.exceptions.AuthenticationException: The client is unauthorized due to authentication failure.

It looks like the wrong message is passed back to the client.

**Comment by uwegeercken** [comment]
Sorry for being unclear. What Kettle tells me is: "Unable to connect to database 'local". I would prefer to have Kettle tell me that it is an authentication problem. Is clearer for the user.

**Comment by mattcasters** [comment]
A fix was released in version 4.0.0. : added source message so you don't have to hit the "Details" button.
