### ISSUE TITLE
Neo4j Cypher - Parameter not used for label

### ISSUE THREAD

**Issue by uwegeercken** [knowbi/knowbi-pentaho-pdi-neo4j-output#97]
In the Neo4j Cypher step, parameters can be used to specfy values. E.g when specifying a property for a node:

merge(st:Station {code: {station}})

But it does not work when a parameter is specified for the node label:

merge(st:{labelStation} {code: {station}})
![grafik](https://user-images.githubusercontent.com/6207140/52168633-749cfb00-272c-11e9-9199-9776a89f2643.png)

**Comment by mattcasters** [comment]
Let's improve the documentation at lease and perhaps leave a hint in the parameters label in the dialog.

**Comment by uwegeercken** [comment]
ok. Agreed

**Comment by mattcasters** [comment]
Changed the label:

```Parameters: (NOTE that parameters for labels are not supported)```

**Comment by mattcasters** [comment]
A fix was released in version 4.0.0.
