### ISSUE TITLE
Neo4j connection problem after using on a sperate machine

### ISSUE THREAD

**Issue by uwegeercken** [knowbi/knowbi-pentaho-pdi-neo4j-output#98]
I have developed a job and some transformations on my laptop. Once finished I moved it to a different laptop and wanted to start it (same PDI and neo4j plugin versions).

The issue was that in the Neo4j steps, in all transformations, the connection to neo4j was shown but when I tried to edit them, I received and error message - the edit connection dialog was not showing up, just an error message (sorry but I don't have it at hand now).

The work around was to create a new connection in one of the steps and then it worked everywhere.

**Comment by uwegeercken** [comment]
Ok. But the connection name is available on the computer where it is moved to. And when you click on "edit" connection, an error occurs.

P.S. will look at the kettle-environment project a little bit later - I am so much into Neo4j right now (with Kettle).

**Comment by uwegeercken** [comment]
I mean: when it is stored in the meta store that's fine but the error error should not show up then. I would expect that I have an empty connection textbox and have to use "new" to define a new one.

**Comment by mattcasters** [comment]
That's not really true Uwe. We shouldn't silently remove metadata. In your scenario you would have to "fix" the steps. Perhaps a warning dialog would be more appropriate.

**Comment by mattcasters** [comment]
A fix was released in version 4.0.0. (warning when you hit OK in the Neo4j Output step)

**Comment by uwegeercken** [comment]
:-)
