### ISSUE TITLE
Checking Use CREATE instead of MERGE causes Label from Fields to be Incorrect

### ISSUE THREAD

**Issue by davidlrosenblum** [knowbi/knowbi-pentaho-pdi-neo4j-output#99]
To recreate have a csv input with at least 2 columns
LabelType and NodeId
Have many rows, altering the LabelType
Map LabelType into the From Label Field
Map NodeId into a property in the From Node, making sure Primary=Y

You will end up with all the nodes having one Label.
When merge is used, this does not happen.

**Comment by mattcasters** [comment]
This is totally correct.  I think the best solution would be to add a feature to start a new UNWIND statement every time you encounter a different label.

**Comment by mattcasters** [comment]
The next observation would be that the same issue applies to dynamic relationships.
In that case we would need to run a new UNWIND statement every time one of the following happens:
* Source node labels clause changes
* Target node labels clause changes
* Relationship label changes

**Comment by mattcasters** [comment]
A fix was released in version 4.0.0.
